version: '3.7'
services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teamone
      MYSQL_USER: teamone
      MYSQL_PASSWORD: AfricanSwallow
      MYSQL_INITDB_SKIP_TZINFO: skip
    volumes:
      - $LOCAL_MARIADB_CONF_DIRECTORY:/etc/mysql/conf.d
      - $LOCAL_MARIADB_DATA_DIRECTORY:/var/lib/mysql
  openteamone:
    image: dockahdockah/openteamone
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mariadb:3306
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - $LOCAL_OPEN_TEAM_ONE_DIRECTORY:/opt/openTeamOneServer
    depends_on:
      - mariadb
