version: '3.7'
services:
  mariadb:
    image: dockahdockah/mariadb-utf8mb4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourSuperStrongRootPassword
      MYSQL_DATABASE: yourDatabaseName
      MYSQL_USER: yourUserName
      MYSQL_PASSWORD: yourSuperStrongUserPassword
      MYSQL_INITDB_SKIP_TZINFO: skip
    volumes:
      - $LOCAL_MARIADB_DATA_DIRECTORY:/var/lib/mysql
#  adminer:
#    image: adminer
#    ports:
#      - "7000:8080"
#    depends_on:
#      - mariadb
  openteamone:
    image: dockahdockah/openteamone
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mariadb:3306
      WAIT_HOSTS_TIMEOUT: 60
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDB53Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/yourDatabaseName
      SPRING_DATASOURCE_USERNAME: yourUserName
      SPRING_DATASOURCE_PASSWORD: yourSuperStrongUserPassword
      SPRING_DATASOURCE_CONNECTIONPROPERTIES: useUnicode=true;characterEncoding=utf-8;serverTimezone=UTC;
#      SECURITY_REQUIRE_SSL: "true"
#      SERVER_SSL_ENABLED: "true"
#      SERVER_SSL_KEY_STORE: /opt/openTeamOneServer/keystores/keystore.p12
#      SERVER_SSL_KEY_STORE_PASSWORD: yourKeyStorePassword
#      SERVER_SSL_KEYSTORETYPE: PKCS12
#      SERVER_SSL_KEYALIAS: yourAlias
    volumes:
      - $LOCAL_OPEN_TEAM_ONE_DIRECTORY:/opt/openTeamOneServer
    depends_on:
      - mariadb
